apiControllers:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
    prefix: '/api'
    name_prefix: 'api_'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
